### ISSUE TITLE
User login not being established.

### ISSUE THREAD

**Issue by paulen** [kylebrowning/drupal-ios-sdk-example#1]
Hello, thanks for the great resources.

Following the steps in the video for the example, when I enter a user's info and hit login, it appears to work and it shows the proper user data in the response status. But after that when I try to perform other actions it says "Unauthorized: Access denied for user anonymous," even when I try to login as admin, or if I click logout it says "Not Acceptable: User is not logged in." So I'm not sure why the connection is not actually getting established.

Appreciate any advice or suggestions, thanks!

**Comment by kylebrowning** [comment]
Which version 6.x or 7.x?

**Comment by paulen** [comment]
Drupal and sdk 7, but example 6 i guess, that's probably the issue huh?

If so do you know what it might take to get the example running with version 7 and what has changed that doesn't work anymore? Thanks very much!

**Comment by kylebrowning** [comment]
Yeah I would say that is the issue, I just tested everything and it seems to be working.

Make sure you are using the 7.x version of the Drupal iOS SDK with the Drupal 7.x example
