### ISSUE TITLE
Can't save the node

### ISSUE THREAD

**Issue by aoifhvul** [kylebrowning/drupal-ios-sdk-example#3]
Hello~

I follow the Demo Setup's video, when I save the node. Appear error message... : Node type is required.

What should I do?

Thanks.

**Comment by kylebrowning** [comment]
Are you supplying a node type?

**Comment by aoifhvul** [comment]
I used Drupal 7, the node type default has "article & page".
But, I type article on the Text Field has same problem. It doesn't work?

http://images.plurk.com/0453bfe99d661f0207ab8270e2f99321.jpg

Need other setup in SDK?

**Comment by kylebrowning** [comment]
Im not sure how you got there.

Are you using drupal-ios-sdk 7.x-3.x, did you grab the latest instead of the tarred download??
Are you using Srervices 3.0? Did you try Services 3.x-dev?

I cannot reproduce this issue.

**Comment by aoifhvul** [comment]
Drupal site version is 7.8.

I using drupal-ios-sdk 7.x-3.x lasted version, and try Services 3.x-dev.
The result is still same problem.

By the way, the structure "Machine name" is node type?

**Comment by antondavidsen** [comment]
I had the same problem, but solved it by downgrading the Services module to 7.x-3.0-rc5

**Comment by kylebrowning** [comment]
Hrmm, I still cant duplicate this issue :(

**Comment by aoifhvul** [comment]
Ok~
But, I want to know the Demo Setup video Drupal version.
Perhaps this is the problem.

**Comment by kylebrowning** [comment]
Demo is Drupal 7, services 3.0

**Comment by aoifhvul** [comment]
The Drupal 7 version is?

**Comment by kylebrowning** [comment]
7.9

**Comment by gogog** [comment]
Kyle, 

Same error: Node type is required.

(1) nodeSave Array contains 'type'.

array: {
    body =     {
        und =         (
                        {
                value = "nodeSave Anonymous User Body";
            }
        );
    };
    language = und;
    name = "";
    sessid = JdMXptqSj6ij4i3u2MHqDmSTHNHe0EuNccXEwZSXJ6Y;
    title = "nodeSave Anonymous User via DrupalSDKCallBack";
    type = article;
}

(2) Drupal 7.9.
(3) Ran both 7.3 and 7.3 dev Services Module - tarred download from Drupal.
(4) Changed to Services 7.x-3.0-rc5 - node save success - Thanks Anton. You rock.

json: {
    nid = 13;
    uri = "http://localhost:8888/drupal79/api/node/13";
}

Aside: I had rewritten DIOSConnect.m to allow for both plist and json (use NSJSONSerialization and tested for feature "if ([NSJSONSerialization class])". This allows me to test new iOS5 features while keeping backward compatibility. Sweet.

Great drupal ios sdk - thanks.

JJ

**Comment by kylebrowning** [comment]
I strongly discourage using rc5 as it has security holes that are addressed in 3.0

I'm going to setup a completely new install(again) and see if I can reproduce this issue.(again)

**Comment by kylebrowning** [comment]
Figured it out, its a bug in DIOS and how params were changed.

This is fixed, Please us services 3.0 or 3.x-dev and update your drupal iOS sdk

**Comment by gogog** [comment]
Kyle,

DIOS update - check
iOS5 - not production system. For testing/development. Focus was on testing of NSJSONSerialization. Security issue noted.

Thanks,
JJ

**Comment by kylebrowning** [comment]
A quick note i integrated JSONKit into DIOS in about 3 lines of code and it seemed to work great.

**Comment by gogog** [comment]
Confirmed fix.
(1) Upgraded to current Services Module (from rc5)
(2) Updated DIOSNode.m

Was able to save node (anon user).
Thx,
JJ
