### ISSUE TITLE
How to use the new node delete ???

### ISSUE THREAD

**Issue by JC2011** [kylebrowning/drupal-ios-sdk-example#8]
I'm trying to use the nodeDelete.

I configured my node with the good nid like this :

DIOSNode *node = [[DIOSNode alloc] init];
    NSMutableDictionary *nodeData = [NSMutableDictionary new];
    [nodeData setValue:[@"73" forKey:@"nid"];
    [node nodeDelete:nodeData success:^(AFHTTPRequestOperation *operation, id responseObject) {
        NSLog(@"node note delete success");
    }failure:^(AFHTTPRequestOperation *operation, NSError *error) {
        NSLog(@"%@",[error description]);
    }];
    [node release];

But this always returned an error  : 
 Error Domain=com.alamofire.networking.error Code=-1011 "Expected status code in (200-299), got 401" UserInfo=0x3f6070 {NSErrorFailingURLKey=http://indev3.theingroup.fr/api/node/73?nid=73, NSLocalizedDescription=Expected status code in (200-299), got 401}

I don't know why. In addition, in my Services 's drupal site, delete operation is authorized.

Could someone help me ?

Best regards,

JC

**Comment by onepartscissors** [comment]
JC, did you manage to find a solution to this one?

Please share the solution you found!
